 drop table if exists bet CASCADE;
 drop table if exists competition CASCADE;
 drop table if exists league CASCADE;
 drop table if exists game CASCADE;
 drop table if exists team CASCADE;
 drop table if exists user CASCADE;
 drop table if exists user_league CASCADE;
 drop sequence if exists hibernate_sequence;
 create sequence hibernate_sequence start with 1 increment by 1;
 create table competition (id_competition bigint PRIMARY KEY AUTO_INCREMENT,  begin_date timestamp not null, competition_name varchar(255), end_date timestamp);
 create table bet (id_bet bigint PRIMARY KEY AUTO_INCREMENT, bet_date timestamp, goals_home integer, goals_visitors integer, id_game bigint not null, id_user bigint not null );
 create table league (id_league bigint PRIMARY KEY AUTO_INCREMENT, creation_date timestamp not null, name varchar(255), id_competition bigint not null);
 create table game (id_game bigint PRIMARY KEY AUTO_INCREMENT, goals_home integer, goals_visitor integer, game_date timestamp, id_competition bigint not null, id_team_home bigint not null, id_team_visitor bigint not null);
 create table team (id bigint PRIMARY KEY AUTO_INCREMENT, country_team varchar(255), name varchar(255), name_logo_team varchar(255), uf varchar(255));
 create table user (id_user bigint PRIMARY KEY AUTO_INCREMENT, creation_user timestamp not null, email varchar(255), id_user_firebase varchar(255), login varchar(255), name_user varchar(255));
 create table user_league (entry_date_league timestamp not null, id_user bigint not null, id_league bigint not null, primary key (id_user, id_league));
 alter table bet add constraint FK914hv0ss39yvfnmhecjcba7gd foreign key (id_game) references game;
 alter table bet add constraint FK6kdkbfstt489lnqvv1949sqvh foreign key (id_user) references user;
 alter table league add constraint FK1xni8kaiugwdosgjfdwenrqmj foreign key (id_competition) references competition;
 alter table game add constraint FK5kww63fvd203p1nrlsi5hjgps foreign key (id_competition) references competition;
 alter table game add constraint FK5bj4ojbjpgt4vs1n41t5gdpry foreign key (id_team_home) references team;
 alter table game add constraint FKpvw8cbsy7gi2idynk60xcmjda foreign key (id_team_visitor) references team;
 alter table user_league add constraint FKnjpmv8g4ih8fal2ee3945s7mb foreign key (id_user) references user;
 alter table user_league add constraint FKbx89ywo3bvvu14n98emw86el9 foreign key (id_league) references league;


INSERT INTO COMPETITION ( BEGIN_DATE , COMPETITION_NAME , END_DATE ) VALUES ('2020-08-08 00:00:00', 'Brasileirao', '2021-03-05 00:00:00');
INSERT INTO TEAM ( COUNTRY_TEAM , NAME , NAME_LOGO_TEAM , UF ) VALUES('Brasil', 'Flamengo', 'Mengo', 'RJ');
INSERT INTO TEAM ( COUNTRY_TEAM , NAME , NAME_LOGO_TEAM , UF ) VALUES('Brasil', 'Atlético', 'Galo', 'MG');
INSERT INTO GAME ( ID_COMPETITION , ID_TEAM_HOME , ID_TEAM_VISITOR , GAME_DATE ) VALUES (1, 1,2,'2020-08-08');
INSERT INTO USER ( CREATION_USER , EMAIL , LOGIN , NAME_USER ) VALUES ('2020-01-01', 'marcelowender@hotmail.com', 'marcelowender', 'Marcelo');
INSERT INTO USER ( CREATION_USER , EMAIL , LOGIN , NAME_USER ) VALUES ('2020-01-01', 'joao@hotmail.com', 'Joaozinho', 'Joao');
INSERT INTO BET ( BET_DATE , GOALS_HOME , GOALS_VISITORS , ID_USER,ID_GAME  ) VALUES ('2020-08-08',1,2,1,1);